export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const AUTHENTICATED_SUCCESS = "AUTHENTICATED_SUCCESS";
export const AUTHENTICATED_FAIL = "AUTHENTICATED_FAIL";
export const USER_LOADED_SUCCESS = "USER_LOADED_SUCCESS";
export const USER_LOADED_FAIL = "USER_LOADED_FAIL";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";
export const ACTIVATION_SUCCESS = "ACTIVATION_SUCCESS";
export const ACTIVATION_FAIL = "ACTIVATION_FAIL";
export const PASSWORD_RESET_FAIL = "PASSWORD_RESET_FAIL";
export const PASSWORD_RESET_SUCCESS = "PASSWORD_RESET_SUCCESS";
export const PASSWORD_RESET_CONFIRM_FAIL = "PASSWORD_RESET_CONFIRM_FAIL";
export const PASSWORD_RESET_CONFIRM_SUCCESS = "PASSWORD_RESET_CONFIRM_SUCCESS";

export const LOAD_TOKENS = "LOAD_TOKENS";

export const RESEND_ACTIVATION_LINK_SUCCESS = "RESEND_ACTIVATION_LINK_SUCCESS";
export const RESEND_ACTIVATION_LINK_FAIL = "RESEND_ACTIVATION_LINK_FAIL";
export const RESEND_ACTIVATION_LINK_RESET = "RESEND_ACTIVATION_LINK_RESET";

export const USER_HAS_PETS = "USER_HAS_PETS";
export const SET_NEW_PET_PROFILE = "SET_NEW_PET_PROFILE";
export const CURRENT_PET_ID = "CURRENT_PET_ID";
export const SET_USER_PET_IDS = "SET_USER_PET_IDS";


export const FETCH_FEED = "FETCH_FEED";
export const ADD_POST = "ADD_POST";
export const SET_FEED_LOADING = "SET_FEED_LOADING";
export const FETCH_POSTS = "FETCH_POSTS";
export const RESET_POST_STATE = "RESET_POST_STATE";
export const UPDATE_CAPTION = "UPDATE_CAPTION";
export const UPDATE_SELECTED_PHOTOS = "UPDATE_SELECTED_PHOTOS";


export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";


export const RESET_STATE = 'RESET_STATE';
